name: EcoJobsBossbar
version: '${project.version}'
main: eu.sengy.ecojobsbossbar.EcoJobsBossbar
api-version: '1.20'
depend: [ EcoJobs, eco ]
commands:
  ecojobsbossbar:
    aliases: [ ejb, jobsbar ]
    description: Default command